### PR TITLE
Removed unused dependency `cli-truncate`

### PR DESCRIPTION
**Pull request by oliverschwendener**
As far as I see this dependency is not used, so we could remove it.

### CODE REVIEW

**Comment by oliverschwendener** [comment]
@argv-minus-one Thanks alot for merging this! Would it be possible to publish a new version to NPM so we can update the package?

**Comment by argv-minus-one** [comment]
Good catch. Thank you.

I'm not going to release just yet because there are some more `npm audit` issues to fix and `npm audit fix` can't fix them. I'll try to figure that out around Monday.

**Comment by argv-minus-one** [comment]
I've released version 1.0.10.

Some `npm audit` issues remain, but I can't yet fix them because of https://github.com/microsoft/rushstack/issues/3018. They only affect this project's `devDependencies`, however, so your project's `npm audit` should be clean now.

**Comment by oliverschwendener** [comment]
Cool, thanks alot!

**Pull request merged**
